Properly shut down the ReloadingModelClientProvider
From our experience the `@PreDestroy` annotation is not reliable, so we
created the `closingBinder` to manage cleanup of closables, executors
and other resources that require cleanup.

Also, two tests were not shutting down the instance anyway.

The result of missing or ineffective cleanup is that the background task
keeps running after the test is complete and spams the logs with error
messages like this:

```
2025-09-29T03:32:30.989-0600	WARN	reloading-model-client-provider	io.starburst.ai.client.ReloadingModelClientProvider	Error refreshing model clients
org.jdbi.v3.core.ConnectionException: java.sql.SQLException: HikariDataSource HikariDataSource (insights) has been closed.
```

(cherry picked from commit c24da4722290942e4685bab026c5c47863d2756c)