[BUFFER] Fix failure of JVM requirements in buffer-service containers
e3d6f552 mandates certain JVM 22 options, but the buffer-service
Dockerfiles didn't have them.  This resulted in containers failing to
start with an error

ERROR: Trino requires -XX:+UnlockDiagnosticVMOptions -XX:G1NumCollectionsKeepPinned=10000000 on Java versions lower than 22.0.2 due to JDK-8329528
(cherry picked from commit 382791a9ffd2d92863fea63b2106e2c250892a53)