Remove id from npm cache job
Error: /home/ubuntu/actions-runner/_work/cork/cork/./.github/actions/setup/action.yml (Line: 111, Col: 13): The identifier 'cache-npm' may not be used more than once within the same scope.
Error: /home/ubuntu/actions-runner/_work/cork/cork/./.github/actions/setup/action.yml (Line: 121, Col: 13): The identifier 'cache-restore-npm' may not be used more than once within the same scope.
Error: GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. /home/ubuntu/actions-runner/_work/cork/cork/./.github/actions/setup/action.yml (Line: 111, Col: 13): The identifier 'cache-npm' may not be used more than once within the same scope.,/home/ubuntu/actions-runner/_work/cork/cork/./.github/actions/setup/action.yml (Line: 121, Col: 13): The identifier 'cache-restore-npm' may not be used more than once within the same scope
(cherry picked from commit f42c4ec1e17fc6443e51a317155b2ebde8f2e2e8)