Return user visible error when catalog is misconfigured
When Driver::connect returns null, most likely it catalog is
misconfigured and error message from the checkState was propagated to
the user making looking obscure.

Before:
Query 20250825_145634_00011_9263i failed: Error listing schemas for
catalog postgresql2:
com.google.common.util.concurrent.UncheckedExecutionException:
java.lang.IllegalStateException: Driver returned null connection, make
sure the connection URL 'jdbc:psql://test' is valid for the driver
org.postgresql.Driver@63a777ba

After:
Query 20250825_150832_00003_52kd7 failed: Error listing schemas for
catalog postgresql: Driver returned null connection, make sure the
connection URL 'jdbc:jdbc:postgresql://localhost:5432/tpch' and
credentials are valid

(cherry picked from commit 846e03b3f630d38b37e8596f8234dd92c93ba855)
(cherry picked from commit 6506a6a131f4f124da292c68c1ec440834af3700)